# Generated by Django 3.0 on 2019-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0002_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='slug'),
        ),
    ]
