# Generated by Django 3.0 on 2019-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0005_auto_20191212_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='fat_100',
            field=models.IntegerField(blank=True, default=0, verbose_name='fat_100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_lvl',
            field=models.CharField(blank=True, max_length=10, verbose_name='fat_lvl'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_100',
            field=models.IntegerField(blank=True, default=0, verbose_name='salt_100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_lvl',
            field=models.CharField(blank=True, max_length=10, verbose_name='salt_lvl'),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_100',
            field=models.IntegerField(blank=True, default=0, verbose_name='saturated_fat_100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_lvl',
            field=models.CharField(blank=True, max_length=10, verbose_name='saturated_fat_lvl'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_100',
            field=models.IntegerField(blank=True, default=0, verbose_name='sugar_100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_lvl',
            field=models.CharField(blank=True, max_length=10, verbose_name='sugar_lvl'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, verbose_name='url'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.TextField(blank=True, verbose_name='store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
