# Generated by Django 3.0 on 2019-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0006_auto_20191216_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat_100',
            field=models.FloatField(blank=True, default=0, verbose_name='fat_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100',
            field=models.FloatField(blank=True, default=0, verbose_name='salt_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_100',
            field=models.FloatField(blank=True, default=0, verbose_name='saturated_fat_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar_100',
            field=models.FloatField(blank=True, default=0, verbose_name='sugar_100g'),
        ),
    ]
