# Generated by Django 3.0 on 2019-12-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0008_auto_20191216_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='openfoodfact.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='fat_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_lvl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='fat_lvl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_grade',
            field=models.CharField(choices=[('', 'N/A'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='salt_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_lvl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='salt_lvl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='saturated_fat_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_lvl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='saturated_fat_lvl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.TextField(blank=True, null=True, verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar_100',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='sugar_100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar_lvl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sugar_lvl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='url'),
        ),
    ]
