# Generated by Django 3.0 on 2019-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0010_auto_20191216_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.TextField(blank=True, null=True, verbose_name='image_url'),
        ),
    ]
