# Generated by Django 3.0 on 2019-12-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfact', '0011_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_category', to='openfoodfact.Category'),
        ),
    ]
